backend:
  name: github
  repo: reidawsome-maker/murnanauto
  branch: main # or master, depending on your primary branch name
  base_url: https://decap-oauth.murnanauto.workers.dev
  auth_endpoint: auth

media_folder: "images/products"
public_folder: "/images/products"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - { label: "Product Title", name: "title", widget: "string" }
      - { label: "SKU", name: "sku", widget: "string" }
      - { label: "Price ($)", name: "price", widget: "number", value_type: "float" }
      - { label: "In Stock Count", name: "stock", widget: "number", default: 0 }
      - { label: "Product Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
